### PR TITLE
- Allow fwa_collection() to accept 'whse_fish' schema.

### PR DESCRIPTION
**Pull request by joethorley**

### CODE REVIEW

**Comment by sebdalgarno** [comment]
have you checked that whse_fish data can be retrieved? (i.e. after it passes that new check) I left it out under the impression that Simon wasn't making those datasets available to us

**Comment by joethorley** [comment]
I was able to get fiss_obstacles_pnt_sp and the various fish stuff ie fiss_fish_obsrvtn_pnt_sp etc - there was something I couldn't get from whse_fish schema but I can't remember which is was .

**Comment by smnorris** [comment]
All the collections currently listed at https://hillcrestgeo.ca/fwapg/collections.html should remain there and you're free to use them. But keep in mind that there is no update schedule - updates happen when I need them at the moment. The FISS data in there come from running these:
- https://github.com/smnorris/bcfishobs
- https://github.com/smnorris/pscis

**Comment by sebdalgarno** [comment]
thanks @joethorley and @smnorris ! merged now

**Comment by smnorris** [comment]
I'll plan to schedule those two scripts to run so the FISS data stays current. 
If I recall correctly, PSCIS BCGW replication is weekly - not sure about the observations/obstructions though.

**Pull request merged**
